# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jihye Leee
baseurl:        "/work"
url:            "http://jihyeleee.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jihye Leee
  url:          http://jihyeleee.com/
  email:        iam.leejihye@gmail.com  
  github: iamleejihye
  twitter: playpingpong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/iamleejihye/work

# Gems

gems:
- jekyll-gist

category-list: [ridi, codi, quoin, blog]